# Generated by Django 5.2.9 on 2025-12-11 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Lançamentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('idIMDB', models.CharField(blank=True, max_length=20, null=True)),
                ('rating', models.CharField()),
                ('poster', models.CharField()),
                ('post_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('idIMDB', models.CharField(blank=True, max_length=20, null=True)),
                ('sinopse', models.TextField()),
                ('rating', models.FloatField()),
                ('during', models.IntegerField()),
                ('poster', models.CharField()),
                ('typeMedia', models.CharField(choices=[('movie', 'Filme'), ('serie', 'Serie')])),
                ('gender', models.ManyToManyField(related_name='media_gender', to='atlas_app.gender')),
            ],
        ),
        migrations.CreateModel(
            name='Popular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='popular_media', to='atlas_app.media')),
            ],
        ),
    ]
