# Generated by Django 5.2.9 on 2025-12-12 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atlas_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Gender',
            new_name='Genres',
        ),
        migrations.RenameField(
            model_name='media',
            old_name='gender',
            new_name='genrer',
        ),
        migrations.RemoveField(
            model_name='media',
            name='during',
        ),
    ]
