# Generated by Django 5.2.9 on 2025-12-12 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atlas_app', '0002_rename_gender_genres_rename_gender_media_genrer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genres',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
