# Generated by Django 5.2.9 on 2025-12-14 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atlas_app', '0003_alter_genres_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='lançamentos',
            name='id_media',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='lancamento_media', to='atlas_app.media'),
            preserve_default=False,
        ),
    ]
