# Generated by Django 5.2.9 on 2025-12-14 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atlas_app', '0004_lançamentos_id_media'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lançamentos',
            name='id_media',
        ),
    ]
