# Generated by Django 5.2.9 on 2025-12-15 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atlas_app', '0005_remove_lançamentos_id_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='genrer',
            field=models.ManyToManyField(blank=True, null=True, related_name='media_gender', to='atlas_app.genres'),
        ),
    ]
