# Generated by Django 5.2.9 on 2025-12-15 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atlas_app', '0006_alter_media_genrer'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='lancament_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
