# Generated by Django 5.2.9 on 2025-12-16 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atlas_app', '0007_media_lancament_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('_key', models.CharField(max_length=255)),
            ],
        ),
    ]
