# Generated by Django 5.2.9 on 2025-12-16 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atlas_app', '0008_apikey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikey',
            name='_key',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='apikey',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
