# Generated by Django 5.2.9 on 2025-12-16 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atlas_app', '0009_alter_apikey__key_alter_apikey_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apikey',
            name='_key',
        ),
        migrations.AddField(
            model_name='apikey',
            name='key',
            field=models.TextField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='apikey',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
