# Generated by Django 5.2.9 on 2025-12-16 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atlas_app', '0010_remove_apikey__key_apikey_key_alter_apikey_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='typeMedia',
            field=models.CharField(choices=[('filme', 'Filme'), ('serie', 'Serie')]),
        ),
    ]
