# Generated by Django 5.2.9 on 2025-12-16 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atlas_app', '0011_alter_media_typemedia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lançamentos',
            name='post_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lançamentos',
            name='poster',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lançamentos',
            name='rating',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
